import type { Metadata } from "next";
// import ApiMockProvider from './api-mock-provider';
import BrowserApiMockProvider from './browser-api-mock-provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BrowserApiMockProvider>
          {children}
        </BrowserApiMockProvider>
      </body>
    </html>
  );
}
